# New secret subclasses: one more for every class, two for each of the five
# new classes; each one is taught by a unique character of the world.
from core import *

# (key, class, color, name, desc, branch desc, skills, abilities, unique)
# skills: list of (key, name, tier, max, level, desc, stats, grants, requires, equip)


def secret_path(out, key, cls, color, name, desc, bdesc, stat_skill, abilities, uniq, extra_monsters=()):
    out.at(f"skills/{cls}.toml", "secret_path")
    subclass(out, key, name, cls, color, desc, secret=True)
    branch(out, key, name, color, bdesc, cls, key)
    sk_key, sk_name, sk_desc, sk_stats = stat_skill
    skill(out, sk_key, sk_name, key, 1, 5, 5, sk_desc, sk_stats)
    prev = sk_key
    for i, (ab_key, sk_name2, sk_desc2, ab) in enumerate(abilities):
        tier, level = [(1, 5), (2, 7), (3, 10)][i]
        req = None if i == 0 else [prev]
        skill(out, ab_key, sk_name2, key, tier, 1, level, sk_desc2, grants=ab_key, requires=req,
              equip=ab.get("equip"))
        prev = ab_key
        ability(out, ab_key, sk_name2, ab.pop("kind"), ab.pop("desc"), ab.pop("color"), **ab)
    for m in extra_monsters:
        monster(out, *m)
    # the teacher and the relics of the quest (written after this call) live with the other masters
    out.at("masters.toml", "secret_paths")
    unique(out, **uniq)


def build(out):
    out.comment("Полководец (воин)")
    secret_path(out, "warlord", "warrior", "#e0a040", ("Полководец", "Warlord"),
                ("Ведёт за собой: боевое знамя, натиск и призрачный легион.", "Leads others: a battle banner, a charge and a ghostly legion."),
                ("Знамя, натиск и легион.", "Banner, charge and legion."),
                ("wl_command", ("Командирский голос", "Commanding Voice"), ("Урон в ближнем бою и здоровье.", "Melee damage and health."), {"melee_pct": 3, "max_hp": 6}),
                [("wl_banner", ("Боевое знамя", "Battle Banner"), ("Знамя вдохновляет вас и союзников.", "A banner inspires you and your allies."),
                  dict(kind="buff", desc=("Вам и союзникам в радиусе 6: +10% урона в ближнем бою, +10% сопротивления всему и +5 брони на 20 с.", "You and allies in radius 6: +10% melee damage, +10% resistance to everything and +5 armor for 20 s."), color="#e0a040",
                       mana=16, cd=30000, radius=6, buff_=buff("battle_banner", ("Боевое знамя", "Battle Banner"), 20000, {"melee_pct": 10, "res_all": 10, "armor": 5}, color="#e0a040"), fx="sound")),
                 ("wl_charge", ("Натиск", "Charge"), ("Рывок к врагу с оглушающим ударом.", "A dash at the enemy with a stunning blow."),
                  dict(kind="dash", desc=("Рывок на 4 клетки: урон и оглушение на 1,5 с первому на пути.", "A 4-tile dash: damage and a 1.5 s stun to the first in the way."), color="#ffb040",
                       mana=12, cd=8000, damage=[10, 16], dmg="blunt", scale="str", k=1.1, range_=4, glyph="~",
                       on_hit=buff("charge_stun", ("Оглушение", "Stun"), 1500, stun=True, color="#ffb040"))),
                 ("wl_legion", ("Легион", "Legion"), ("Призрачные солдаты встают в строй рядом с вами.", "Ghostly soldiers fall in beside you."),
                  dict(kind="summon", desc=("Три призрачных солдата на 40 с.", "Three ghostly soldiers for 40 s."), color="#c0d0ff",
                       mana=30, cd=50000, count=3, summon="wl_soldier", duration=40000, fx="spirit"))],
                dict(key="svyatopolk", name=("Святополк", "Svyatopolk"), title=("Старый воевода", "the Old Voivode"), color="#e0a040", model="old_voivode",
                     persona=("Седой воевода в потёртой кольчуге, водивший полки в сотне сражений. Говорит по-командирски, коротко и веско, ценит смелость и верность строю.", "A grey voivode in worn mail who led regiments in a hundred battles. Speaks like a commander, briefly and weightily, values courage and keeping formation."),
                     greeting=("Равняйсь, {player}! Шучу. Садись, послушай старика.", "Fall in, {player}! Just kidding. Sit down, listen to an old man."),
                     about=[("Я водил полки, когда твои деды ещё в люльках пищали.", "I led regiments when your grandfathers were still squealing in cradles."),
                            ("Один воин — это меч. Сотня воинов под знаменем — это стена.", "One warrior is a sword. A hundred warriors under a banner are a wall.")],
                     biomes=["plains", "hills", "cursed"], quest="slay", target="dark_knight", champion=("Чёрный маршал", "the Black Marshal"),
                     offer=("Чёрный маршал собирает войско мертвецов в проклятых землях. Сломи его — и я научу тебя вести за собой.", "The Black Marshal gathers an army of the dead in the cursed lands. Break him — and I will teach you to lead."),
                     done=("Маршал пал! Ты бьёшься как полководец. Отныне за тобой пойдут — бери знамя.", "The Marshal has fallen! You fight like a warlord. From now on they will follow you — take the banner."),
                     reward="subclass:warlord"),
                extra_monsters=[("wl_soldier", ("Призрачный солдат", "Ghostly Soldier"), "@", "#c0d0ff", 60, [5, 9], 4, "slash", 200, 950, "melee", "frontline", "town_guard", {"poison": 100, "shadow": 25})])

    out.comment("Ассасин (плут)")
    secret_path(out, "assassin", "rogue", "#b03a4a", ("Ассасин", "Assassin"),
                ("Удар из тени, дымовая завеса и смертельная метка.", "A strike from the shadows, a smoke screen and a deadly mark."),
                ("Тень и смерть.", "Shadow and death."),
                ("as_shadow_arts", ("Искусство тени", "Shadow Arts"), ("Урон тьмой и урон из засады.", "Shadow damage and ambush damage."), {"shadow_pct": 6, "ambush_pct": 5}),
                [("as_shadow_strike", ("Удар из тени", "Shadow Strike"), ("Удар тьмой, втрое сильнее из невидимости или в спину.", "A shadow blow, three times stronger from stealth or in the back."),
                  dict(kind="strike", desc=("Урон тьмой; из невидимости или по отвлечённой цели — втрое больше.", "Shadow damage; triple from stealth or at a distracted target."), color="#b03a4a",
                       mana=10, cd=5000, damage=[10, 16], dmg="shadow", scale="dex", k=1.1, backstab=3, glyph="!", equip="weapon")),
                 ("as_smoke_bomb", ("Дымовая бомба", "Smoke Bomb"), ("Вы исчезаете в облаке дыма.", "You vanish in a cloud of smoke."),
                  dict(kind="buff", desc=("Невидимость и +30% к скорости бега на 6 с.", "Stealth and +30% running speed for 6 s."), color="#808090",
                       mana=12, cd=20000, buff_=buff("smoke", ("В дыму", "In Smoke"), 6000, {"move_speed": 30}, stealth=True, color="#808090"), fx="smoke")),
                 ("as_death_mark", ("Метка смерти", "Death Mark"), ("Метка, медленно и верно убивающая цель.", "A mark that slowly but surely kills the target."),
                  dict(kind="projectile", desc=("Тьма терзает цель 10 с и снижает её защиту от тьмы на 25%.", "Darkness torments the target for 10 s and lowers its shadow protection by 25%."), color="#8a1a3a",
                       mana=18, cd=12000, damage=[6, 10], dmg="shadow", scale="dex", k=0.8, range_=9, speed=25, glyph="x",
                       on_hit=buff("death_mark", ("Метка смерти", "Death Mark"), 10000, {"res_shadow": -25}, dot=12, dmg="shadow", color="#8a1a3a"), fx="mark"))],
                dict(key="ten", name=("Тень", "Shade"), title=("Мастер гильдии убийц", "Guildmaster of Assassins"), color="#b03a4a", model="assassin_master",
                     persona=("Безликий мастер гильдии убийц в чёрном. Говорит тихо, вежливо и страшно, о цене жизни и о тишине; никогда не называет настоящего имени.", "The faceless master of the assassins' guild, dressed in black. Speaks quietly, politely and frighteningly, of the price of a life and of silence; never says a real name."),
                     greeting=("Ты меня нашёл, {player}. Значит, я этого хотел.", "You found me, {player}. That means I wanted you to."),
                     about=[("У гильдии нет имени. У меня — тоже.", "The guild has no name. Neither do I."),
                            ("Чёрная роза — наш знак. Её оставляют на телах.", "The black rose is our sign. It is left on the bodies.")],
                     biomes=["cursed", "plains", "forest"], quest="relics", target="black_rose", count=5, sources=["cursed", "fortress", "plains"],
                     offer=("Наши розы растащили культисты и разбойники. Верни пять чёрных роз — и гильдия примет тебя.", "Cultists and bandits have carried off our roses. Bring back five black roses — and the guild will accept you."),
                     done=("Пять роз. Ни одной лишней крови... почти. Ты — ассасин. Не ищи меня — я найду тебя сам.", "Five roses. Not a drop of needless blood... almost. You are an assassin. Don't look for me — I will find you."),
                     reward="subclass:assassin"))
    relic(out, "black_rose", ("Чёрная роза", "Black Rose"), "#3a0a1a", ("Знак гильдии убийц. Нужна Тени.", "The sign of the assassins' guild. Shade needs it."))

    out.comment("Архимаг (маг)")
    secret_path(out, "archmage", "mage", "#7a8aff", ("Архимаг", "Archmage"),
                ("Чистая тайная магия: сферы, щит маны и метеор.", "Pure arcane magic: orbs, a mana shield and a meteor."),
                ("Высшая магия.", "High magic."),
                ("am_mastery", ("Высшая магия", "High Magic"), ("Сила заклинаний и урон тайной магией.", "Spell power and arcane damage."), {"spell_pct": 5, "arcane_pct": 5}),
                [("am_arcane_orb", ("Тайная сфера", "Arcane Orb"), ("Медленная сфера, взрывающаяся тайной магией.", "A slow orb that bursts with arcane magic."),
                  dict(kind="projectile", desc=("Взрыв тайной магии в радиусе 2.", "An arcane blast in radius 2."), color="#9aa0ff",
                       mana=14, cd=5000, damage=[14, 22], dmg="arcane", scale="int", k=1.4, range_=9, radius=2, speed=60, glyph="O")),
                 ("am_mana_shield", ("Щит маны", "Mana Shield"), ("Мерцающий щит из чистой маны.", "A shimmering shield of pure mana."),
                  dict(kind="buff", desc=("12 с: +25% сопротивления всему и +10 брони.", "12 s: +25% resistance to everything and +10 armor."), color="#a0b0ff",
                       mana=16, cd=30000, buff_=buff("mana_shield", ("Щит маны", "Mana Shield"), 12000, {"res_all": 25, "armor": 10}, color="#a0b0ff"), fx="shield arcane")),
                 ("am_meteor", ("Метеор", "Meteor"), ("С неба падает пылающий камень.", "A flaming stone falls from the sky."),
                  dict(kind="projectile", desc=("Огромный взрыв в радиусе 3: огонь и тайная магия пополам.", "A huge blast in radius 3: fire and arcane magic in halves."), color="#ff7a3a",
                       mana=40, cd=20000, damage=[34, 50], split=["fire", "arcane"], scale="int", k=2.4, range_=10, radius=3, speed=80, glyph="@", fx="meteor"))],
                dict(key="arkadiy", name=("Аркадий", "Arkadiy"), title=("Последний архимаг", "the Last Archmage"), color="#7a8aff", model="archmage_npc",
                     persona=("Древний архимаг павшей академии, высокомерный и рассеянный. Говорит длинно и учёно, ценит знание, презирает невежество и спешку.", "An ancient archmage of a fallen academy, haughty and absent-minded. Speaks at length and learnedly, values knowledge, despises ignorance and haste."),
                     greeting=("Ты умеешь читать, {player}? Уже неплохо для начала.", "Can you read, {player}? Not bad for a start."),
                     about=[("Академия сгорела, но знание не горит. Оно лишь прячется в кристаллах.", "The academy burned, but knowledge does not burn. It only hides in crystals."),
                            ("Магия — это не взмах посохом. Это сорок лет за книгами.", "Magic is not a wave of a staff. It is forty years over books.")],
                     biomes=["hills", "tundra", "plains"], quest="relics", target="arcane_crystal", count=5, sources=["ice", "temple", "cave"],
                     offer=("Кристаллы с записями академии растащили твари подземелий. Верни пять — и я передам тебе высшую магию.", "The creatures of the dungeons carried off the crystals with the academy's records. Return five — and I will pass the high magic to you."),
                     done=("Кристаллы... знания живы! Ты достоин зваться архимагом. Не трать силу на пустяки.", "The crystals... the knowledge lives! You are worthy of being called an archmage. Do not waste the power on trifles."),
                     reward="subclass:archmage"))
    relic(out, "arcane_crystal", ("Кристалл академии", "Academy Crystal"), "#9aa0ff", ("В кристалле застыли строки заклинаний. Нужен Аркадию.", "Lines of spells are frozen in the crystal. Arkadiy needs it."))

    out.comment("Оракул (жрец)")
    secret_path(out, "oracle", "priest", "#c0e0ff", ("Оракул", "Oracle"),
                ("Видит будущее: пророчества, цепи света и рок.", "Sees the future: prophecies, chains of light and fate."),
                ("Предвидение.", "Foresight."),
                ("or_foresight", ("Предвидение", "Foresight"), ("Уклонение и крит. шанс.", "Dodge and crit chance."), {"dodge": 3, "crit": 2}),
                [("or_prophecy", ("Пророчество", "Prophecy"), ("Вы и союзники видите удары врагов заранее.", "You and allies see enemy blows coming."),
                  dict(kind="buff", desc=("Вам и союзникам в радиусе 5: +15% уклонения и +10% крит. шанса на 15 с.", "You and allies in radius 5: +15% dodge and +10% crit chance for 15 s."), color="#c0e0ff",
                       mana=14, cd=25000, radius=5, buff_=buff("prophecy", ("Пророчество", "Prophecy"), 15000, {"dodge": 15, "crit": 10}, color="#c0e0ff"), fx="star")),
                 ("or_divine_chain", ("Цепь света", "Chain of Light"), ("Свет перескакивает с врага на врага.", "Light leaps from enemy to enemy."),
                  dict(kind="chain", desc=("Свет перескакивает на 5 врагов.", "Light leaps to 5 enemies."), color="#fff8c0",
                       mana=14, cd=6000, damage=[10, 15], dmg="holy", scale="int", k=1.2, range_=8, count=5, glyph="+")),
                 ("or_fate", ("Предначертание", "Fate"), ("Судьба настигает всех врагов вокруг.", "Fate overtakes every enemy around."),
                  dict(kind="nova", desc=("Свет в радиусе 4 и оглушение на 2 с.", "Light in radius 4 and a 2 s stun."), color="#e0f0ff",
                       mana=30, cd=18000, damage=[18, 28], dmg="holy", scale="int", k=1.5, radius=4, glyph="*",
                       on_hit=buff("fated", ("Предначертание", "Fate"), 2000, stun=True, color="#e0f0ff"), fx="time"))],
                dict(key="vedana", name=("Ведана", "Vedana"), title=("Вещая", "the Seer"), color="#c0e0ff", model="oracle_npc",
                     persona=("Слепая провидица с повязкой на глазах, видящая будущее. Говорит загадками и притчами, часто отвечает раньше, чем спросят.", "A blind seer with a cloth over her eyes who sees the future. Speaks in riddles and parables, often answers before being asked."),
                     greeting=("Я знала, что ты придёшь, {player}. И знаю, что спросишь.", "I knew you would come, {player}. And I know what you will ask."),
                     about=[("Глаза мне не нужны. Я вижу то, что будет, а не то, что есть.", "I don't need eyes. I see what will be, not what is."),
                            ("Кости древних оракулов шепчут. Слушай.", "The bones of ancient oracles whisper. Listen.")],
                     biomes=["desert", "hills", "plains"], quest="relics", target="oracle_bone", count=5, sources=["temple", "desert", "crypt"],
                     offer=("Кости оракулов разнесли мертвецы гробниц. Принеси пять — и я открою тебе глаза, которыми вижу сама.", "The dead of the tombs scattered the oracle bones. Bring five — and I will open the eyes I see with."),
                     done=("Кости поют... Теперь и ты слышишь будущее. Ты — оракул. Не бойся того, что увидишь.", "The bones sing... Now you hear the future too. You are an oracle. Do not fear what you see."),
                     reward="subclass:oracle"))
    relic(out, "oracle_bone", ("Кость оракула", "Oracle Bone"), "#e8e0c8", ("Исписанная знаками кость. Нужна Ведане.", "A bone covered with signs. Vedana needs it."))

    out.comment("Огненный провидец (шаман)")
    secret_path(out, "fireseer", "shaman", "#ff6a2a", ("Огненный провидец", "Fireseer"),
                ("Духи огня и лава: извержения и пламенные духи.", "Fire spirits and lava: eruptions and flame spirits."),
                ("Пламя недр.", "The flame of the depths."),
                ("fs_magma_blood", ("Кровь магмы", "Magma Blood"), ("Урон огнём и защита от него.", "Fire damage and protection from it."), {"fire_pct": 7, "res_fire": 4}),
                [("fs_lava_burst", ("Выброс лавы", "Lava Burst"), ("Сгусток лавы поджигает врагов.", "A clot of lava sets enemies on fire."),
                  dict(kind="projectile", desc=("Огонь в радиусе 1 и горение на 4 с.", "Fire in radius 1 and burning for 4 s."), color="#ff6a2a",
                       mana=8, cd=3000, damage=[10, 15], dmg="fire", scale="int", k=1.1, range_=8, radius=1, speed=35, glyph="*",
                       on_hit=buff("lava_burn", ("Горение", "Burning"), 4000, dot=4, dmg="fire", color="#ff6a2a"))),
                 ("fs_flame_spirits", ("Духи пламени", "Flame Spirits"), ("Огненные духи бьются за вас.", "Fire spirits fight for you."),
                  dict(kind="summon", desc=("Два огненных беса на 40 с.", "Two fire imps for 40 s."), color="#ff8a3a",
                       mana=18, cd=30000, count=2, summon="imp_minion", duration=40000, fx="fire")),
                 ("fs_eruption", ("Извержение", "Eruption"), ("Земля вокруг взрывается огнём.", "The ground around erupts in fire."),
                  dict(kind="nova", desc=("Огонь в радиусе 4: огромный урон.", "Fire in radius 4: huge damage."), color="#ff4a1a",
                       mana=32, cd=16000, damage=[22, 34], dmg="fire", scale="int", k=1.7, radius=4, glyph="^", fx="eruption"))],
                dict(key="ugryum", name=("Угрюм", "Ugryum"), title=("Хранитель жерла", "Keeper of the Crater"), color="#ff6a2a", model="fire_keeper",
                     persona=("Мрачный шаман с обожжённым лицом, живущий у вулкана. Говорит отрывисто, о пламени, пепле и гневе земли; не терпит холодных людей.", "A gloomy shaman with a burned face who lives by the volcano. Speaks curtly, of flame, ash and the wrath of the earth; can't stand cold people."),
                     greeting=("Ты пахнешь холодом, {player}. Подойди к огню.", "You smell of cold, {player}. Come closer to the fire."),
                     about=[("Вулкан — сердце мира. Я слушаю, как оно бьётся.", "The volcano is the heart of the world. I listen to it beat."),
                            ("Огонь не злой. Он голодный.", "Fire is not evil. It is hungry.")],
                     biomes=["ash", "desert", "hills"], quest="slay", target="salamander", champion=("Огнежор", "Fire-Eater"),
                     offer=("Саламандра Огнежор пожирает духов пламени. Убей её — и духи станут твоими.", "The salamander Fire-Eater devours the flame spirits. Kill it — and the spirits will become yours."),
                     done=("Огнежор мёртв, духи свободны. Они выбрали тебя, провидец.", "Fire-Eater is dead, the spirits are free. They have chosen you, seer."),
                     reward="subclass:fireseer"))

    out.comment("Пожиратель душ (чернокнижник)")
    secret_path(out, "soul_eater", "warlock", "#9a2aff", ("Пожиратель душ", "Soul Eater"),
                ("Вырывает души врагов и питается ими.", "Rips out enemies' souls and feeds on them."),
                ("Голод души.", "Soul hunger."),
                ("se_hunger", ("Голод", "Hunger"), ("Вампиризм и урон тьмой.", "Life leech and shadow damage."), {"life_leech": 1, "shadow_pct": 4}),
                [("se_soul_rip", ("Вырвать душу", "Soul Rip"), ("Тьма вырывает кусок души врага.", "Darkness rips out a piece of an enemy's soul."),
                  dict(kind="projectile", desc=("Урон тьмой, половина возвращается здоровьем.", "Shadow damage, half of it returns as health."), color="#9a2aff",
                       mana=10, cd=4000, damage=[12, 18], dmg="shadow", scale="int", k=1.2, leech=50, range_=8, speed=30, glyph="*")),
                 ("se_soul_armor", ("Доспех из душ", "Soul Armor"), ("Пленённые души заслоняют вас.", "Captured souls shield you."),
                  dict(kind="buff", desc=("15 с: +30% сопротивления тьме, +6 брони, +4 к восстановлению здоровья.", "15 s: +30% shadow resistance, +6 armor, +4 health regeneration."), color="#b05aff",
                       mana=14, cd=25000, buff_=buff("soul_armor", ("Доспех из душ", "Soul Armor"), 15000, {"res_shadow": 30, "armor": 6, "hp_regen": 4}, color="#b05aff"), fx="shield shadow")),
                 ("se_harvest", ("Жатва душ", "Soul Harvest"), ("Души всех врагов вокруг идут вам на пищу.", "The souls of every enemy around become your food."),
                  dict(kind="nova", desc=("Тьма в радиусе 4: урон, треть возвращается здоровьем.", "Darkness in radius 4: damage, a third returns as health."), color="#7a1aff",
                       mana=32, cd=18000, damage=[18, 28], dmg="shadow", scale="int", k=1.5, leech=30, radius=4, glyph="%"))],
                dict(key="bezymyanny", name=("Безымянный", "the Nameless"), title=("Тот, кто съел своё имя", "One Who Ate His Name"), color="#9a2aff", model="nameless",
                     persona=("Иссохший чернокнижник, поглотивший столько душ, что забыл собственное имя. Говорит шёпотом, путает «я» и «мы», голоден всегда.", "A withered warlock who devoured so many souls that he forgot his own name. Speaks in a whisper, mixes up 'I' and 'we', is always hungry."),
                     greeting=("Мы чуем тебя, {player}. Твоя душа... вкусная. Шучу. Наверное.", "We smell you, {player}. Your soul... is tasty. Just kidding. Probably."),
                     about=[("У меня было имя. Я его съел. Оно было последним.", "I had a name. I ate it. It was the last one."),
                            ("Души — как свечи. Одни горят ярко, другие чадят.", "Souls are like candles. Some burn bright, others smoke.")],
                     biomes=["cursed", "swamp"], quest="slay", target="banshee", champion=("Плакальщица Ночи", "the Night Mourner"),
                     offer=("Банши Плакальщица крадёт души, что принадлежат нам. Убей её — и научим тебя есть души.", "The banshee called the Night Mourner steals souls that belong to us. Kill her — and we will teach you to eat souls."),
                     done=("Её души теперь наши... и твои. Ешь, Пожиратель. Только не всех сразу.", "Her souls are ours now... and yours. Eat, Soul Eater. Just not all at once."),
                     reward="subclass:soul_eater"))

    out.comment("Хранитель луны (друид)")
    secret_path(out, "moonkeeper", "druid", "#a0b0ff", ("Хранитель луны", "Moonkeeper"),
                ("Лунный свет и звездопад: тайная магия и холод ночи.", "Moonlight and starfall: arcane magic and the cold of the night."),
                ("Свет луны.", "Moonlight."),
                ("mk_moonlight", ("Лунный свет", "Moonlight"), ("Урон тайной магией и холодом.", "Arcane and cold damage."), {"arcane_pct": 5, "cold_pct": 5}),
                [("mk_moonbeam", ("Лунный луч", "Moonbeam"), ("Холодный луч луны замедляет врага.", "A cold moonbeam slows an enemy."),
                  dict(kind="projectile", desc=("Тайная магия и замедление на 40% на 4 с.", "Arcane magic and a 40% slow for 4 s."), color="#a0b0ff",
                       mana=8, cd=3000, damage=[10, 15], dmg="arcane", scale="int", k=1.1, range_=9, speed=15, glyph="|",
                       on_hit=buff("moonbeam_chill", ("Лунный холод", "Moon Chill"), 4000, {"move_speed": -40}, color="#a0b0ff"), fx="lance star")),
                 ("mk_starfall", ("Звездопад", "Starfall"), ("Звёзды падают на врагов.", "Stars fall on enemies."),
                  dict(kind="projectile", desc=("Тайная магия в радиусе 3.", "Arcane magic in radius 3."), color="#e0e8ff",
                       mana=20, cd=9000, damage=[16, 24], dmg="arcane", scale="int", k=1.4, range_=10, radius=3, speed=50, glyph="*", fx="rain star")),
                 ("mk_lunar_eclipse", ("Лунное затмение", "Lunar Eclipse"), ("Затмение лишает врагов магии.", "An eclipse robs enemies of magic."),
                  dict(kind="nova", desc=("Тайная магия в радиусе 5 и печать молчания на 3 с.", "Arcane magic in radius 5 and a 3 s seal of silence."), color="#6a7aff",
                       mana=32, cd=18000, damage=[18, 28], dmg="arcane", scale="int", k=1.5, radius=5, glyph="o",
                       on_hit=buff("eclipse_silence", ("Затмение", "Eclipse"), 3000, silence=True, color="#6a7aff"), fx="eclipse"))],
                dict(key="lunyana", name=("Луняна", "Lunyana"), title=("Сова ночи", "Owl of the Night"), color="#a0b0ff", model="moon_druid",
                     persona=("Бледная друидесса с совой на плече, бодрствующая только ночью. Говорит тихо и певуче, о луне, звёздах и снах.", "A pale druidess with an owl on her shoulder who is awake only at night. Speaks softly and melodiously, of the moon, the stars and dreams."),
                     greeting=("Ты не спишь, {player}? Хорошо. Луна любит неспящих.", "You're not asleep, {player}? Good. The moon loves the sleepless."),
                     about=[("Днём я сплю. Днём мир слишком громкий.", "I sleep by day. The world is too loud by day."),
                            ("Каждая звезда — чей-то сон. Некоторые сны падают.", "Every star is someone's dream. Some dreams fall.")],
                     biomes=["forest", "swamp", "tundra"], quest="slay", target="ghost", champion=("Бледный странник", "the Pale Wanderer"),
                     offer=("Призрак Бледный странник ворует сны спящих. Упокой его — и луна откроется тебе.", "The ghost called the Pale Wanderer steals the dreams of sleepers. Lay him to rest — and the moon will open to you."),
                     done=("Сны вернулись к спящим. Луна видит тебя, хранитель.", "The dreams have returned to the sleepers. The moon sees you, keeper."),
                     reward="subclass:moonkeeper"))

    out.comment("Повелитель призраков (некромант)")
    secret_path(out, "wraithlord", "necromancer", "#a0c8d0", ("Повелитель призраков", "Wraithlord"),
                ("Призраки, вопль мёртвых и бесплотная форма.", "Ghosts, the wail of the dead and an ethereal form."),
                ("Мир теней.", "The world of shades."),
                ("wr_ethereal", ("Бесплотность", "Ethereality"), ("Уклонение и защита от тьмы.", "Dodge and protection from darkness."), {"dodge": 3, "res_shadow": 5}),
                [("wr_summon_ghosts", ("Зов призраков", "Call of Ghosts"), ("Призраки служат вам.", "Ghosts serve you."),
                  dict(kind="summon", desc=("Два призрака на 40 с.", "Two ghosts for 40 s."), color="#a0c8d0",
                       mana=18, cd=30000, count=2, summon="wr_ghost", duration=40000, fx="spirit")),
                 ("wr_wail", ("Вопль мёртвых", "Wail of the Dead"), ("Вопль ранит и обессиливает врагов.", "A wail that wounds and weakens enemies."),
                  dict(kind="nova", desc=("Тьма в радиусе 4 и −30% скорости атаки врагов на 6 с.", "Darkness in radius 4 and −30% enemy attack speed for 6 s."), color="#80a8b0",
                       mana=16, cd=10000, damage=[10, 16], dmg="shadow", scale="int", k=1.1, radius=4, glyph="%",
                       on_hit=buff("wailed", ("Ужас", "Dread"), 6000, {"attack_speed": -30}, color="#80a8b0"), fx="spirit")),
                 ("wr_spectral_form", ("Призрачная форма", "Spectral Form"), ("Вы становитесь почти бесплотным.", "You become almost incorporeal."),
                  dict(kind="buff", desc=("10 с: +40% уклонения, +20% скорости бега, +30% сопротивления физическому урону.", "10 s: +40% dodge, +20% running speed, +30% physical resistance."), color="#c0e0f0",
                       mana=20, cd=40000, buff_=buff("spectral_form", ("Призрачная форма", "Spectral Form"), 10000, {"dodge": 40, "move_speed": 20, "res_physical": 30}, color="#c0e0f0"), fx="form spirit"))],
                dict(key="trizna", name=("Тризна", "Trizna"), title=("Плакальщица мёртвых", "Mourner of the Dead"), color="#a0c8d0", model="mourner",
                     persona=("Седая плакальщица, что говорит с мёртвыми на погостах. Говорит печально и тепло, о покое, памяти и неупокоенных душах.", "A grey mourner who speaks with the dead in graveyards. Speaks sadly and warmly, of peace, memory and restless souls."),
                     greeting=("Ты живой, {player}? Тогда помолчи немного. Они слушают.", "Are you alive, {player}? Then be quiet for a while. They are listening."),
                     about=[("Мёртвые не злые. Им просто холодно и одиноко.", "The dead are not evil. They are just cold and lonely."),
                            ("Я оплакала тысячу душ. Некоторые до сих пор приходят сказать спасибо.", "I have mourned a thousand souls. Some still come to say thank you.")],
                     biomes=["cursed", "swamp", "plains"], quest="boss", target="lich",
                     offer=("Лич Морвен держит души в клетке своей филактерии. Освободи их — и призраки пойдут за тобой добровольно.", "The lich Morwen keeps souls caged in her phylactery. Free them — and the ghosts will follow you willingly."),
                     done=("Души свободны... и некоторые остались с тобой. Береги их, повелитель призраков.", "The souls are free... and some have stayed with you. Look after them, lord of ghosts."),
                     reward="subclass:wraithlord"),
                extra_monsters=[("wr_ghost", ("Призрак-слуга", "Servant Ghost"), "G", "#a0c8d0", 45, [4, 8], 0, "shadow", 170, 900, "melee", "skirmisher", "ghost", {"physical": 50, "poison": 100, "holy": -50})])

    # ---- two for each new class ----
    out.comment("Звёздный лучник (следопыт)")
    secret_path(out, "starshot", "ranger", "#e0e8ff", ("Звёздный лучник", "Starshot"),
                ("Стрелы из звёздного света: тайная магия на огромном расстоянии.", "Arrows of starlight: arcane magic at a huge range."),
                ("Стрелы звёзд.", "Arrows of the stars."),
                ("ss_celestial", ("Небесная меткость", "Celestial Aim"), ("Урон тайной магией и в дальнем бою.", "Arcane and ranged damage."), {"arcane_pct": 6, "ranged_pct": 4}),
                [("ss_star_arrow", ("Звёздная стрела", "Star Arrow"), ("Стрела света летит очень далеко.", "An arrow of light flies very far."),
                  dict(kind="projectile", desc=("Тайная магия на 13 клеток.", "Arcane magic over 13 tiles."), color="#e0e8ff",
                       mana=8, cd=2500, damage=[12, 18], dmg="arcane", scale="dex", k=1.2, range_=13, speed=12, glyph="dir", fx="star")),
                 ("ss_constellation", ("Созвездие", "Constellation"), ("Пять звёздных стрел разом.", "Five star arrows at once."),
                  dict(kind="projectile", desc=("Пять стрел тайной магии веером.", "Five arcane arrows in a fan."), color="#c0d0ff",
                       mana=16, cd=8000, damage=[8, 12], dmg="arcane", scale="dex", k=0.9, range_=11, count=5, speed=15, glyph="*", fx="star")),
                 ("ss_supernova", ("Сверхновая", "Supernova"), ("Стрела взрывается, как рождение звезды.", "An arrow bursts like the birth of a star."),
                  dict(kind="projectile", desc=("Взрыв в радиусе 4: тайная магия и огонь пополам.", "A blast in radius 4: arcane magic and fire in halves."), color="#fff0c0",
                       mana=36, cd=20000, damage=[30, 46], split=["arcane", "fire"], scale="dex", k=2.2, range_=12, radius=4, speed=40, glyph="*", fx="supernova"))],
                dict(key="astra", name=("Астра", "Astra"), title=("Небесная лучница", "the Celestial Archer"), color="#e0e8ff", model="star_archer",
                     persona=("Высокая лучница с серебряными волосами и луком, сияющим как звезда. Говорит мечтательно, о небе, звёздах и падающих огнях.", "A tall archer with silver hair and a bow shining like a star. Speaks dreamily, of the sky, the stars and falling lights."),
                     greeting=("Смотри вверх, {player}. Там всегда кто-то целится.", "Look up, {player}. Someone is always taking aim up there."),
                     about=[("Я стреляю звёздами. Они возвращаются на небо, когда я промахиваюсь.", "I shoot stars. They return to the sky when I miss."),
                            ("Звёздная пыль падает на землю каждую ночь. Её подбирают не те.", "Star dust falls to the ground every night. The wrong ones pick it up.")],
                     biomes=["hills", "tundra", "plains"], quest="relics", target="star_dust", count=6, sources=["hills", "tundra", "ice"],
                     offer=("Твари севера собирают звёздную пыль, как сороки. Принеси шесть горстей — и я научу тебя стрелять звёздами.", "The creatures of the north collect star dust like magpies. Bring six handfuls — and I will teach you to shoot stars."),
                     done=("Пыль снова сияет. Натягивай тетиву, звёздный лучник, — небо твоё.", "The dust shines again. Draw the string, starshot — the sky is yours."),
                     reward="subclass:starshot"))
    relic(out, "star_dust", ("Звёздная пыль", "Star Dust"), "#e0e8ff", ("Мерцающая пыль павших звёзд. Нужна Астре.", "The shimmering dust of fallen stars. Astra needs it."))

    out.comment("Дикая охота (следопыт)")
    secret_path(out, "wild_hunt", "ranger", "#7a9a6a", ("Дикая охота", "Wild Hunt"),
                ("Призрачная свора и рог охоты.", "A spectral pack and the horn of the hunt."),
                ("Гон.", "The chase."),
                ("wh_hunt_lord", ("Владыка охоты", "Lord of the Hunt"), ("Здоровье и урон любого боя.", "Health and damage of every kind of fight."), {"max_hp": 6, "melee_pct": 3, "ranged_pct": 3}),
                [("wh_spectral_hounds", ("Призрачная свора", "Spectral Pack"), ("Три призрачных пса гонят добычу.", "Three spectral hounds chase the prey."),
                  dict(kind="summon", desc=("Три призрачных пса на 30 с.", "Three spectral hounds for 30 s."), color="#9ab08a",
                       mana=18, cd=30000, count=3, summon="wh_hound", duration=30000, fx="spirit")),
                 ("wh_horn", ("Рог охоты", "Horn of the Hunt"), ("Звук рога гонит вас и союзников вперёд.", "The sound of the horn drives you and your allies onward."),
                  dict(kind="buff", desc=("Вам и союзникам в радиусе 6: +20% скорости бега и атаки на 15 с.", "You and allies in radius 6: +20% running and attack speed for 15 s."), color="#c0b080",
                       mana=12, cd=25000, radius=6, buff_=buff("hunt_horn", ("Рог охоты", "Horn of the Hunt"), 15000, {"move_speed": 20, "attack_speed": 20}, color="#c0b080"), fx="sound")),
                 ("wh_huntsman", ("Призрачный егерь", "Spectral Huntsman"), ("Сам Егерь Дикой охоты приходит на зов.", "The Huntsman of the Wild Hunt himself answers the call."),
                  dict(kind="summon", desc=("Призрачный егерь на 45 с.", "A spectral huntsman for 45 s."), color="#8ab07a",
                       mana=30, cd=50000, count=1, summon="wh_huntsman", duration=45000, fx="spirit"))],
                dict(key="gon", name=("Гон", "Gon"), title=("Ловчий Дикой охоты", "Huntsman of the Wild Hunt"), color="#7a9a6a", model="wild_huntsman",
                     persona=("Призрачный ловчий в рогатом шлеме, ведущий Дикую охоту по ночам. Говорит гулко, о погоне, добыче и вечной охоте.", "A spectral huntsman in a horned helm who leads the Wild Hunt by night. Speaks hollowly, of the chase, the prey and the eternal hunt."),
                     greeting=("Ты слышишь рог, {player}? Нет? Ещё услышишь.", "Do you hear the horn, {player}? No? You will."),
                     about=[("Моя охота не кончается. Добыча сменяется, охотник — никогда.", "My hunt never ends. The prey changes, the hunter never does."),
                            ("Свора бежит за тем, кто бежит. Не беги.", "The pack runs after whoever runs. Don't run.")],
                     biomes=["forest", "plains", "hills"], quest="slay", target="wolf", champion=("Седой Вожак", "the Grey Leader"),
                     offer=("Седой Вожак увёл мою свору за собой. Убей его — и свора признает тебя.", "The Grey Leader has led my pack away. Kill him — and the pack will acknowledge you."),
                     done=("Свора вернулась... и смотрит на тебя. Труби в рог, ловчий.", "The pack has returned... and is looking at you. Sound the horn, huntsman."),
                     reward="subclass:wild_hunt"),
                extra_monsters=[("wh_hound", ("Призрачный пёс", "Spectral Hound"), "w", "#9ab08a", 50, [5, 8], 1, "shadow", 120, 750, "melee", "skirmisher", "wolf", {"physical": 30, "poison": 100}),
                                ("wh_huntsman", ("Призрачный егерь", "Spectral Huntsman"), "@", "#8ab07a", 140, [10, 16], 4, "pierce", 170, 1000, "ranged", "ranged", "hunter", {"physical": 30, "poison": 100})])

    out.comment("Рыцарь Грааля (паладин)")
    secret_path(out, "grail_knight", "paladin", "#ffe8a0", ("Рыцарь Грааля", "Grail Knight"),
                ("Хранитель святой чаши: исцеление, святое копьё и аватар света.", "Keeper of the holy cup: healing, a holy lance and an avatar of light."),
                ("Сила чаши.", "The power of the cup."),
                ("gk_grail", ("Глоток из чаши", "Sip from the Cup"), ("Сила лечения и урон светом.", "Healing power and holy damage."), {"heal_pct": 6, "holy_pct": 4}),
                [("gk_grail_light", ("Свет Грааля", "Light of the Grail"), ("Чаша изливает исцеление на всех вокруг.", "The cup pours healing on everyone around."),
                  dict(kind="heal", desc=("Большое исцеление вас и союзников в радиусе 6.", "A big heal for you and allies in radius 6."), color="#ffe8a0",
                       mana=20, cd=12000, damage=[26, 38], scale="int", k=1.8, radius=6, glyph="+", fx="holy")),
                 ("gk_holy_lance", ("Святое копьё", "Holy Lance"), ("Копьё света пронзает и оглушает.", "A lance of light pierces and stuns."),
                  dict(kind="projectile", desc=("Свет и оглушение на 1 с.", "Light and a 1 s stun."), color="#fff4c0",
                       mana=12, cd=6000, damage=[14, 20], dmg="holy", scale="str", k=1.2, range_=9, speed=15, glyph="/",
                       on_hit=buff("lance_stun", ("Оглушение", "Stun"), 1000, stun=True, color="#fff4c0"), fx="lance")),
                 ("gk_avatar", ("Аватар света", "Avatar of Light"), ("Вы становитесь живым светом.", "You become living light."),
                  dict(kind="buff", desc=("15 с: +25% сопротивления всему, +40% урона светом, +20% в ближнем бою.", "15 s: +25% resistance to everything, +40% holy damage, +20% melee."), color="#ffffd0",
                       mana=30, cd=60000, buff_=buff("light_avatar", ("Аватар света", "Avatar of Light"), 15000, {"res_all": 25, "holy_pct": 40, "melee_pct": 20}, color="#ffffd0"), fx="form holy"))],
                dict(key="perceval", name=("Персиваль", "Perceval"), title=("Хранитель Чаши", "Keeper of the Cup"), color="#ffe8a0", model="grail_keeper",
                     persona=("Благородный седой рыцарь, всю жизнь искавший святую чашу и нашедший её. Говорит возвышенно и учтиво, о чистоте, служении и подвиге.", "A noble grey knight who sought the holy cup all his life and found it. Speaks loftily and courteously, of purity, service and great deeds."),
                     greeting=("Мир тебе, {player}. Твоё сердце чисто? Чаша скажет.", "Peace to you, {player}. Is your heart pure? The cup will tell."),
                     about=[("Я искал Чашу сорок лет. Она была у меня в руках с самого начала.", "I sought the Cup for forty years. It was in my hands from the very beginning."),
                            ("Чаша не даёт силу. Она показывает, сколько силы в тебе.", "The Cup does not give strength. It shows how much strength is in you.")],
                     biomes=["plains", "forest", "hills"], quest="boss", target="orc_warlord",
                     offer=("Орочий вождь Гром осквернил часовню Чаши под горами. Сразите его — и Чаша примет вас.", "The orc warlord Grom has desecrated the chapel of the Cup beneath the mountains. Slay him — and the Cup will accept you."),
                     done=("Часовня очищена. Пейте из Чаши, рыцарь Грааля, и несите свет.", "The chapel is cleansed. Drink from the Cup, Grail Knight, and carry the light."),
                     reward="subclass:grail_knight"))

    out.comment("Клятвопреступник (паладин)")
    secret_path(out, "oathbreaker", "paladin", "#7a3a8a", ("Клятвопреступник", "Oathbreaker"),
                ("Паладин, нарушивший клятву: свет и тьма в одном ударе, аура ужаса.", "A paladin who broke the oath: light and darkness in one blow, an aura of dread."),
                ("Нарушенная клятва.", "The broken oath."),
                ("ob_broken_oath", ("Нарушенная клятва", "Broken Oath"), ("Урон тьмой и вампиризм.", "Shadow damage and life leech."), {"shadow_pct": 6, "life_leech": 0.6}),
                [("ob_dark_smite", ("Тёмная кара", "Dark Smite"), ("Удар светом и тьмой разом.", "A blow of light and darkness at once."),
                  dict(kind="strike", desc=("Урон тьмой и светом пополам.", "Shadow and holy damage in halves."), color="#9a4aaa",
                       mana=10, cd=4000, damage=[12, 18], split=["shadow", "holy"], scale="str", k=1.1, glyph="!", equip="weapon", fx="shadow")),
                 ("ob_aura_dread", ("Аура ужаса", "Aura of Dread"), ("Враги вокруг слабеют от страха.", "Enemies around weaken with fear."),
                  dict(kind="nova", desc=("Враги в радиусе 4 на 8 с теряют 15% сопротивления всему и 15% скорости атаки.", "Enemies in radius 4 lose 15% resistance to everything and 15% attack speed for 8 s."), color="#6a2a7a",
                       mana=14, cd=14000, damage=[0, 0], radius=4, glyph="%",
                       on_hit=buff("dread", ("Ужас", "Dread"), 8000, {"res_all": -15, "attack_speed": -15}, color="#6a2a7a"), fx="shadow")),
                 ("ob_unholy_avatar", ("Нечестивый аватар", "Unholy Avatar"), ("Тьма заполняет вас целиком.", "Darkness fills you completely."),
                  dict(kind="buff", desc=("15 с: +40% урона тьмой, +8% вампиризма, +10 брони.", "15 s: +40% shadow damage, +8% life leech, +10 armor."), color="#4a1a5a",
                       mana=28, cd=60000, buff_=buff("unholy_avatar", ("Нечестивый аватар", "Unholy Avatar"), 15000, {"shadow_pct": 40, "life_leech": 8, "armor": 10}, color="#4a1a5a"), fx="form shadow"))],
                dict(key="mordred", name=("Мордред", "Mordred"), title=("Падший паладин", "the Fallen Paladin"), color="#7a3a8a", model="fallen_paladin",
                     persona=("Падший паладин в почерневших латах, нарушивший клятву ради мести. Говорит горько и насмешливо, о лицемерии святош и цене клятв.", "A fallen paladin in blackened plate who broke his oath for revenge. Speaks bitterly and mockingly, of the hypocrisy of the pious and the price of oaths."),
                     greeting=("Ещё один праведник, {player}? Посмотрим, надолго ли.", "Another righteous one, {player}? Let's see how long it lasts."),
                     about=[("Я поклялся защищать. Защищал. А потом понял, кого.", "I swore to protect. I protected. And then I realized whom."),
                            ("Свет и тьма — две руки одного бога. Я просто перестал прятать левую.", "Light and darkness are two hands of one god. I just stopped hiding the left one.")],
                     biomes=["cursed", "plains"], quest="slay", target="risen", champion=("Падший брат Ансельм", "Fallen Brother Anselm"),
                     offer=("Мой бывший брат по ордену, Ансельм, восстал из могилы и всё ещё судит живых. Положи этому конец — и я научу тебя силе нарушенной клятвы.", "My former brother of the order, Anselm, has risen from the grave and still judges the living. Put an end to it — and I will teach you the power of a broken oath."),
                     done=("Ансельм наконец мёртв. Видишь? Клятвы — для мертвецов. Ты свободен, клятвопреступник.", "Anselm is finally dead. You see? Oaths are for the dead. You are free, oathbreaker."),
                     reward="subclass:oathbreaker"))

    out.comment("Пьяный мастер (монах)")
    secret_path(out, "drunken_master", "monk", "#e0b060", ("Пьяный мастер", "Drunken Master"),
                ("Шатается, как пьяный, но не пропускает ни удара; плюётся огненным вином.", "Staggers like a drunk but never misses a blow; spits fiery wine."),
                ("Пьяный кулак.", "The drunken fist."),
                ("dm_stagger", ("Пошатывание", "Stagger"), ("Уклонение и крит. шанс.", "Dodge and crit chance."), {"dodge": 3, "crit": 2}),
                [("dm_drunken_flail", ("Пьяный шквал", "Drunken Flurry"), ("Пять беспорядочных, но метких ударов.", "Five erratic but accurate blows."),
                  dict(kind="strike", desc=("Пять ударов по одной цели.", "Five blows at one target."), color="#e0b060",
                       mana=12, cd=6000, damage=[4, 8], dmg="blunt", scale="dex", k=0.6, count=5, glyph="!")),
                 ("dm_sway", ("Качка", "Sway"), ("Вас невозможно задеть.", "You are impossible to hit."),
                  dict(kind="buff", desc=("10 с: +40% уклонения.", "10 s: +40% dodge."), color="#f0d080",
                       mana=10, cd=25000, buff_=buff("sway", ("Качка", "Sway"), 10000, {"dodge": 40}, color="#f0d080"), fx="wind")),
                 ("dm_fire_spit", ("Огненный плевок", "Fire Spit"), ("Глоток крепкого вина — и струя огня.", "A sip of strong wine — and a jet of fire."),
                  dict(kind="projectile", desc=("Три струи огня веером.", "Three jets of fire in a fan."), color="#ff8a3a",
                       mana=18, cd=9000, damage=[12, 18], dmg="fire", scale="dex", k=1.1, range_=5, count=3, speed=25, glyph="*"))],
                dict(key="khmel", name=("Хмель", "Khmel"), title=("Бродячий мастер", "the Wandering Master"), color="#e0b060", model="drunken_npc",
                     persona=("Весёлый старый монах с кувшином, вечно навеселе, но непобедимый в бою. Говорит заплетающимся языком, шутит и икает, мудрость прячет в прибаутках.", "A cheerful old monk with a jug, forever tipsy but undefeated in battle. Speaks with a slurred tongue, jokes and hiccups, hides wisdom in sayings."),
                     greeting=("Ик! Ты кто? А, {player}! Садись, выпьем! Ик!", "Hic! Who are you? Ah, {player}! Sit down, let's drink! Hic!"),
                     about=[("Трезвый боец думает. Пьяный — просто бьёт. Ик.", "A sober fighter thinks. A drunk one just hits. Hic."),
                            ("Мой учитель пил тридцать лет и не проиграл ни одного боя. Ни одного трезвого боя.", "My teacher drank for thirty years and never lost a fight. Not a single sober fight.")],
                     biomes=["plains", "forest", "hills"], quest="relics", target="old_wine", count=5, sources=["plains", "hills", "forest"],
                     offer=("Разбойники растащили мои кувшины со старым вином! Верни пять — и научу пьяному кулаку. Ик!", "Bandits have carried off my jugs of old wine! Bring back five — and I'll teach you the drunken fist. Hic!"),
                     done=("Моё вино! Ик! Держи кувшин, ученик. Пей — и бей. Ты — пьяный мастер!", "My wine! Hic! Take the jug, student. Drink — and strike. You are a drunken master!"),
                     reward="subclass:drunken_master"))
    relic(out, "old_wine", ("Кувшин старого вина", "Jug of Old Wine"), "#c08040", ("Пахнет так, что голова кружится. Нужен Хмелю.", "It smells so strong your head spins. Khmel needs it."))

    out.comment("Кулак дракона (монах)")
    secret_path(out, "dragon_fist", "monk", "#ff5a3a", ("Кулак дракона", "Dragon Fist"),
                ("Ци дракона: огненные удары и взлёт дракона.", "The chi of the dragon: fiery blows and the dragon's ascent."),
                ("Дух дракона.", "The spirit of the dragon."),
                ("df_dragon_spirit", ("Дух дракона", "Dragon Spirit"), ("Урон в ближнем бою и огнём.", "Melee and fire damage."), {"melee_pct": 5, "fire_pct": 5}),
                [("df_dragon_palm", ("Ладонь дракона", "Dragon Palm"), ("Огненный удар, оставляющий ожог.", "A fiery blow that leaves a burn."),
                  dict(kind="strike", desc=("Огонь и дробящий урон пополам, горение на 4 с.", "Fire and blunt damage in halves, burning for 4 s."), color="#ff5a3a",
                       mana=10, cd=4000, damage=[12, 18], split=["fire", "blunt"], scale="str", k=1.1, glyph="!",
                       on_hit=buff("dragon_burn", ("Горение", "Burning"), 4000, dot=4, dmg="fire", color="#ff5a3a"), fx="fire")),
                 ("df_dragon_dash", ("Бросок дракона", "Dragon Rush"), ("Огненный рывок сквозь врагов.", "A fiery dash through enemies."),
                  dict(kind="dash", desc=("Рывок на 5 клеток с огненным ударом.", "A 5-tile dash with a fiery blow."), color="#ff7a3a",
                       mana=12, cd=7000, damage=[12, 18], dmg="fire", scale="str", k=1.1, range_=5, glyph="~")),
                 ("df_dragon_ascend", ("Взлёт дракона", "Dragon Ascent"), ("Вы взмываете вверх в столбе пламени.", "You soar up in a pillar of flame."),
                  dict(kind="nova", desc=("Огонь в радиусе 4 и оглушение на 1,5 с.", "Fire in radius 4 and a 1.5 s stun."), color="#ff3a1a",
                       mana=30, cd=16000, damage=[22, 32], dmg="fire", scale="str", k=1.6, radius=4, glyph="^",
                       on_hit=buff("ascent_stun", ("Оглушение", "Stun"), 1500, stun=True, color="#ff3a1a"), fx="eruption"))],
                dict(key="shen", name=("Шэнь", "Shen"), title=("Ученик дракона", "Disciple of the Dragon"), color="#ff5a3a", model="dragon_monk",
                     persona=("Суровый монах с драконьими татуировками, медитирующий у вулкана. Говорит размеренно, о дыхании, огне и дисциплине.", "A stern monk with dragon tattoos who meditates by the volcano. Speaks measuredly, of breath, fire and discipline."),
                     greeting=("Дыши, {player}. Глубже. Ещё. Теперь можешь говорить.", "Breathe, {player}. Deeper. Again. Now you may speak."),
                     about=[("Дракон спит в каждом из нас. Почти у всех — крепко.", "A dragon sleeps in each of us. In almost everyone — soundly."),
                            ("Огонь — это дыхание, которое стало ударом.", "Fire is a breath that has become a blow.")],
                     biomes=["ash", "hills", "desert"], quest="boss", target="magma_lord",
                     offer=("Игнар, Владыка Магмы, пьёт пламя дракона из недр вулкана. Победи его — и дракон проснётся в тебе.", "Ignar, Lord of Magma, drinks the dragon's flame from the depths of the volcano. Defeat him — and the dragon will awaken in you."),
                     done=("Пламя вернулось в недра. Дракон проснулся. Дыши огнём, ученик.", "The flame has returned to the depths. The dragon has awakened. Breathe fire, disciple."),
                     reward="subclass:dragon_fist"))

    out.comment("Певец тризны (скальд)")
    secret_path(out, "dirge", "skald", "#8a7aaa", ("Певец тризны", "Dirgesinger"),
                ("Погребальные песни: тьма, плач и пляска смерти.", "Funeral songs: darkness, lament and the dance of death."),
                ("Песни смерти.", "Songs of death."),
                ("dg_dirge", ("Погребальный напев", "Funeral Chant"), ("Урон тьмой и сила заклинаний.", "Shadow damage and spell power."), {"shadow_pct": 6, "spell_pct": 2}),
                [("dg_funeral_song", ("Погребальная песнь", "Funeral Song"), ("Песнь, от которой стынет кровь.", "A song that makes the blood run cold."),
                  dict(kind="nova", desc=("Тьма в радиусе 4 и тьма терзает врагов 6 с.", "Darkness in radius 4, and darkness torments enemies for 6 s."), color="#8a7aaa",
                       mana=14, cd=9000, damage=[8, 13], dmg="shadow", scale="int", k=1.0, radius=4, glyph="%",
                       on_hit=buff("dirge_doom", ("Плач", "Lament"), 6000, dot=5, dmg="shadow", color="#8a7aaa"), fx="shadow")),
                 ("dg_requiem", ("Реквием", "Requiem"), ("Скорбная нота перелетает от врага к врагу.", "A mournful note flies from enemy to enemy."),
                  dict(kind="chain", desc=("Тьма перескакивает на 4 врагов.", "Darkness leaps to 4 enemies."), color="#6a5a8a",
                       mana=16, cd=7000, damage=[12, 18], dmg="shadow", scale="int", k=1.2, range_=8, count=4, glyph="%")),
                 ("dg_dance_of_death", ("Пляска смерти", "Dance of Death"), ("Вы и союзники пьёте жизнь врагов.", "You and allies drink the life of enemies."),
                  dict(kind="buff", desc=("Вам и союзникам в радиусе 5: +6% вампиризма и +15% урона в ближнем бою на 12 с.", "You and allies in radius 5: +6% life leech and +15% melee damage for 12 s."), color="#a08ac0",
                       mana=24, cd=40000, radius=5, buff_=buff("dance_of_death", ("Пляска смерти", "Dance of Death"), 12000, {"life_leech": 6, "melee_pct": 15}, color="#a08ac0"), fx="shadow"))],
                dict(key="vran", name=("Вран", "Vran"), title=("Поющий на тризнах", "Singer of the Wake"), color="#8a7aaa", model="dirge_singer",
                     persona=("Бледный скальд в чёрном плаще с вороньими перьями, поющий на поминках. Говорит нараспев и печально, о мёртвых героях и последних песнях.", "A pale skald in a black cloak with raven feathers who sings at wakes. Speaks in a sing-song, sad voice, of dead heroes and last songs."),
                     greeting=("Я спою и на твоей тризне, {player}. Но не сегодня.", "I will sing at your wake too, {player}. But not today."),
                     about=[("Каждому герою — своя последняя песня. Я знаю их все.", "Every hero has a last song. I know them all."),
                            ("Могильные цветы растут только там, где плакали.", "Grave flowers grow only where someone wept.")],
                     biomes=["cursed", "swamp", "tundra"], quest="relics", target="grave_flower", count=5, sources=["crypt", "cursed", "swamp"],
                     offer=("Принеси мне пять могильных цветов — их носят мертвецы склепов и болот. Тогда я научу тебя песням тризны.", "Bring me five grave flowers — the dead of the crypts and swamps carry them. Then I will teach you the songs of the wake."),
                     done=("Цветы... Теперь твоя песня зазвучит над павшими врагами. Пой, певец тризны.", "The flowers... Now your song will sound over fallen enemies. Sing, singer of the wake."),
                     reward="subclass:dirge"))
    relic(out, "grave_flower", ("Могильный цветок", "Grave Flower"), "#8a7aaa", ("Бледный цветок с запахом холодной земли. Нужен Врану.", "A pale flower smelling of cold earth. Vran needs it."))

    out.comment("Рунный скальд (скальд)")
    secret_path(out, "rune_skald", "skald", "#80c0ff", ("Рунный скальд", "Rune Skald"),
                ("Руны льда, грома и защиты, вырезанные голосом.", "Runes of ice, thunder and protection, carved with the voice."),
                ("Песни рун.", "Songs of runes."),
                ("rs_rune_lore", ("Знание рун", "Rune Lore"), ("Мана и сопротивление всему.", "Mana and resistance to everything."), {"max_mp": 5, "res_all": 2}),
                [("rs_rune_of_frost", ("Руна стужи", "Rune of Frost"), ("Руна холода сковывает врагов вокруг.", "A rune of cold binds enemies around."),
                  dict(kind="nova", desc=("Холод в радиусе 3 и замедление на 50% на 5 с.", "Cold in radius 3 and a 50% slow for 5 s."), color="#80c0ff",
                       mana=12, cd=8000, damage=[10, 15], dmg="cold", scale="int", k=1.0, radius=3, glyph="*",
                       on_hit=buff("rune_frost", ("Руна стужи", "Rune of Frost"), 5000, {"move_speed": -50, "attack_speed": -20}, color="#80c0ff"), fx="rune frost")),
                 ("rs_rune_of_thunder", ("Руна грома", "Rune of Thunder"), ("Брошенная руна взрывается молнией.", "A thrown rune bursts with lightning."),
                  dict(kind="projectile", desc=("Молния в радиусе 2.", "Lightning in radius 2."), color="#fff06a",
                       mana=14, cd=6000, damage=[14, 20], dmg="lightning", scale="int", k=1.3, range_=9, radius=2, speed=30, glyph="R", fx="rune")),
                 ("rs_rune_of_aegis", ("Руна щита", "Rune of Aegis"), ("Руна защиты над вами и союзниками.", "A rune of protection over you and your allies."),
                  dict(kind="buff", desc=("Вам и союзникам в радиусе 5: +12 брони и +15% сопротивления всему на 15 с.", "You and allies in radius 5: +12 armor and +15% resistance to everything for 15 s."), color="#a0d0ff",
                       mana=22, cd=40000, radius=5, buff_=buff("rune_aegis", ("Руна щита", "Rune of Aegis"), 15000, {"armor": 12, "res_all": 15}, color="#a0d0ff"), fx="shield"))],
                dict(key="einar", name=("Эйнар", "Einar"), title=("Резчик рун", "the Rune Carver"), color="#80c0ff", model="rune_carver",
                     persona=("Могучий северный скальд, вырезающий руны на камнях. Говорит громко и нараспев, о богах, рунах и подвигах предков.", "A mighty northern skald who carves runes on stones. Speaks loudly and in a chant, of gods, runes and the deeds of ancestors."),
                     greeting=("Хей, {player}! Руны сказали, что ты придёшь. Руны не врут. Почти.", "Hey, {player}! The runes said you would come. Runes don't lie. Almost."),
                     about=[("Каждая руна — это песня, застывшая в камне.", "Every rune is a song frozen in stone."),
                            ("Ярл Ледобород украл мой камень рун. Камень весит как бык.", "Jarl Frostbeard stole my rune stone. The stone weighs as much as a bull.")],
                     biomes=["tundra", "hills"], quest="boss", target="frost_jarl",
                     offer=("Ярл Ледобород держит мой камень рун в своих чертогах. Убей его — и я научу тебя петь руны.", "Jarl Frostbeard keeps my rune stone in his halls. Kill him — and I will teach you to sing runes."),
                     done=("Камень снова мой! Слушай песню рун, брат, — теперь она и твоя.", "The stone is mine again! Listen to the song of runes, brother — now it is yours too."),
                     reward="subclass:rune_skald"))

    out.comment("Чумной доктор (зельевар)")
    secret_path(out, "plague_doctor", "brewer", "#6a8a4a", ("Чумной доктор", "Plague Doctor"),
                ("Лечит болезнь болезнью: чумные склянки и чёрная смерть для врагов.", "Cures disease with disease: plague flasks and the black death for enemies."),
                ("Миазмы.", "Miasma."),
                ("pd_miasma", ("Миазмы", "Miasma"), ("Урон ядом и защита от него.", "Poison damage and protection from it."), {"poison_pct": 7, "res_poison": 5}),
                [("pd_plague_flask", ("Чумная склянка", "Plague Flask"), ("Склянка с заразой разбивается среди врагов.", "A flask of contagion shatters among enemies."),
                  dict(kind="projectile", desc=("Яд в радиусе 2 и болезнь на 8 с.", "Poison in radius 2 and disease for 8 s."), color="#6a8a4a",
                       mana=12, cd=5000, damage=[8, 12], dmg="poison", scale="int", k=1.0, range_=8, radius=2, speed=45, glyph="o",
                       on_hit=buff("black_plague", ("Чума", "Plague"), 8000, {"res_poison": -15}, dot=5, dmg="poison", color="#6a8a4a"), fx="flask")),
                 ("pd_leech_cure", ("Пиявки", "Leeches"), ("Старый докторский способ — помогает.", "The old doctor's remedy — it works."),
                  dict(kind="heal", desc=("Исцеляет вас и союзников в радиусе 4.", "Heals you and allies in radius 4."), color="#8a6a4a",
                       mana=14, cd=10000, damage=[18, 26], scale="int", k=1.4, radius=4, glyph="+", fx="blood")),
                 ("pd_black_death", ("Чёрная смерть", "Black Death"), ("Мор накрывает всех врагов вокруг.", "Pestilence covers every enemy around."),
                  dict(kind="nova", desc=("Яд в радиусе 5 и страшная болезнь на 10 с.", "Poison in radius 5 and a terrible disease for 10 s."), color="#3a4a2a",
                       mana=34, cd=18000, damage=[14, 22], dmg="poison", scale="int", k=1.3, radius=5, glyph="%",
                       on_hit=buff("black_death", ("Чёрная смерть", "Black Death"), 10000, {"res_poison": -20, "attack_speed": -15}, dot=12, dmg="poison", color="#3a4a2a")))],
                dict(key="korvus", name=("Корвус", "Korvus"), title=("Лекарь в маске", "the Masked Healer"), color="#6a8a4a", model="plague_doc",
                     persona=("Таинственный доктор в маске с клювом, бродящий там, где мор. Говорит сухо и по-учёному, о болезнях, лекарствах и о том, что яд и лекарство — одно и то же.", "A mysterious doctor in a beaked mask who wanders wherever plague is. Speaks dryly and learnedly, of diseases, cures and how poison and medicine are one and the same."),
                     greeting=("Покажите язык, {player}. Хм. Жить будете. Пока.", "Show me your tongue, {player}. Hm. You'll live. For now."),
                     about=[("Яд и лекарство отличаются только дозой.", "Poison and medicine differ only in the dose."),
                            ("Я лечил мор в трёх городах. В двух — успешно.", "I treated the plague in three cities. In two — successfully.")],
                     biomes=["swamp", "cursed", "plains"], quest="slay", target="bog_witch", champion=("Гниль-Матушка", "Mother Rot"),
                     offer=("Болотная ведьма Гниль-Матушка варит мор и шлёт его на деревни. Останови её — и я передам тебе своё ремесло.", "The bog witch Mother Rot brews plague and sends it upon the villages. Stop her — and I will pass my craft on to you."),
                     done=("Матушка больше не варит. Держите маску, коллега. Лечите — и убивайте — с умом.", "Mother is brewing no more. Take the mask, colleague. Heal — and kill — wisely."),
                     reward="subclass:plague_doctor"))

    out.comment("Трансмутатор (зельевар)")
    secret_path(out, "transmuter", "brewer", "#ffd040", ("Трансмутатор", "Transmuter"),
                ("Превращает металлы и плоть: ртутная скорость, железный голем и золотая буря.", "Transmutes metals and flesh: quicksilver speed, an iron golem and a golden storm."),
                ("Великое делание.", "The Great Work."),
                ("tm_transmute", ("Превращение", "Transmutation"), ("Больше золота и урон тайной магией.", "More gold and arcane damage."), {"gold_find": 15, "arcane_pct": 4}),
                [("tm_quicksilver", ("Ртуть в крови", "Quicksilver Blood"), ("Тело становится текучим, как ртуть.", "The body becomes fluid as quicksilver."),
                  dict(kind="buff", desc=("12 с: +30% скорости бега, +15% скорости атаки, +10% уклонения.", "12 s: +30% running speed, +15% attack speed, +10% dodge."), color="#d0d8e0",
                       mana=12, cd=25000, buff_=buff("quicksilver", ("Ртуть в крови", "Quicksilver Blood"), 12000, {"move_speed": 30, "attack_speed": 15, "dodge": 10}, color="#d0d8e0"), fx="wind")),
                 ("tm_iron_golem", ("Железный голем", "Iron Golem"), ("Голем из превращённого железа.", "A golem of transmuted iron."),
                  dict(kind="summon", desc=("Железный голем на 45 с.", "An iron golem for 45 s."), color="#a0a0b0",
                       mana=26, cd=50000, count=1, summon="tm_golem", duration=45000, fx="steel")),
                 ("tm_golden_storm", ("Золотая буря", "Golden Storm"), ("Вихрь расплавленного золота.", "A whirlwind of molten gold."),
                  dict(kind="nova", desc=("Тайная магия и огонь пополам в радиусе 4.", "Arcane magic and fire in halves in radius 4."), color="#ffd040",
                       mana=32, cd=16000, damage=[22, 32], split=["arcane", "fire"], scale="int", k=1.6, radius=4, glyph="$", fx="gold"))],
                dict(key="flamel", name=("Фламель", "Flamel"), title=("Древний алхимик", "the Ancient Alchemist"), color="#ffd040", model="old_alchemist",
                     persona=("Древний алхимик, нашедший философский камень и живущий уже триста лет. Говорит неспешно и загадочно, о превращениях, золоте и вечности.", "An ancient alchemist who found the philosopher's stone and has lived for three hundred years. Speaks unhurriedly and mysteriously, of transmutation, gold and eternity."),
                     greeting=("Триста лет я жду ученика, {player}. Ты опоздал всего на двести.", "For three hundred years I have waited for a student, {player}. You are only two hundred late."),
                     about=[("Свинец в золото — это просто. Человека в мудреца — вот задача.", "Lead into gold is easy. A man into a sage — that is the task."),
                            ("Камень у меня есть. Нет времени им пользоваться. Ирония.", "I have the stone. I have no time to use it. Irony.")],
                     biomes=["desert", "hills", "ash"], quest="relics", target="quicksilver_ore", count=5, sources=["volcano", "cave", "ash"],
                     offer=("Для великого делания нужна живая ртутная руда — её глотают твари недр. Принеси пять кусков — и я открою тебе тайну превращений.", "The Great Work needs living quicksilver ore — the creatures of the depths swallow it. Bring five pieces — and I will reveal the secret of transmutation."),
                     done=("Руда живая, чудесно! Смотри и учись: всё есть всё. Ты — трансмутатор.", "The ore is alive, wonderful! Watch and learn: everything is everything. You are a transmuter."),
                     reward="subclass:transmuter"),
                extra_monsters=[("tm_golem", ("Железный голем", "Iron Golem"), "Q", "#a0a0b0", 240, [12, 20], 10, "blunt", 260, 1300, "melee", "frontline", "golem", {"poison": 100, "slash": 30, "pierce": 30, "lightning": -40}, "m_stomp")])
    relic(out, "quicksilver_ore", ("Ртутная руда", "Quicksilver Ore"), "#d0d8e0", ("Кусок руды, по которому бегут живые капли. Нужен Фламелю.", "A lump of ore with living droplets running across it. Flamel needs it."))
