[package]
name = "ratas-core"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[lints]
workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
regex = "1"
flate2 = "1"
bincode = "1"
ureq = { version = "2", features = ["json"] }
